ask/ask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('qa.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ask/qa/urls.py
#URLs for app 'qa'

from django.urls import path
from . import views

app_name = 'qa'
urlpatterns = [
	path('', views.index, name='index'),
	path('question/<int:question_id>/', views.question, name='question'),
	path('ask/', views.ask, name='ask'),
	path('popular/', views.popular, name='popular'),
	path('tagged/<slug:slug>/', views.tagged, name='tagged'),
	path('question_like/', views.question_like, name='question_like'),
	path('answer_like/', views.answer_like, name='answer_like'),
	path('answer_correct/', views.answer_correct, name='answer_correct'),
]

ask/users/urls.py
#URLs for app 'users'

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	path('', include('django.contrib.auth.urls')),
	path('signup/', views.signup, name='signup'),
	path('settings/', views.show_profile, name='show_profile'),
	path('settings/update/', views.update_profile, name='update_profile'),
]

ask/qa/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
import re

# Create your models here.

class QuestionManager(models.Manager): 
	def new(self):
		return self.order_by('-added_at')

	def popular(self):
		return self.annotate(likes_count=Count('likes')).order_by('-likes_count')

class Question(models.Model):
	title = models.CharField(max_length=255)
	text = models.TextField()
	added_at = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	likes = models.ManyToManyField(User, related_name='question_like_user', blank=True)
	tags = TaggableManager()
	objects = QuestionManager()

	def __str__(self):
		return self.title

	def get_url(self):
		return reverse('qa:question', args=[self.id])

class Answer(models.Model):
	text = models.TextField()
	added_at = models.DateTimeField(auto_now_add=True)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	likes = models.ManyToManyField(User, related_name='answer_like_user', blank=True)
	is_correct = models.BooleanField(default=False)

	def __str__(self):
		return f'answer {self.id}'

ask/qa/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
#from django.core.exceptions import ValidationError
#import re


class AskForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['title', 'text', 'tags']
		labels = {'title': 'Title', 'text': 'Question', 'tags': 'Tags'}
		
"""
class AskForm(forms.Form):
	title = forms.CharField(max_length=255, label="Title")
	text = forms.CharField(widget=forms.Textarea, label="Question")
	tags = forms.CharField(max_length=255, label="Tags", required=False)

	def clean_tags(self):
		tags_string = self.cleaned_data['tags']
		tags_string = tags_string.strip().lower()
		if re.match(r'^[\w\s]*$', tags_string):
			tags=set()
			tags_set = set(tags_string.split())
			for tag in tags_set:
				if not Tag.objects.filter(title=tag).first():
					Tag.objects.create(title=tag)
				tags.add(Tag.objects.get(title=tag))
			return tags
		else:
			raise ValidationError('Use only letters, digits or undercover')
"""

class AnswerForm(forms.ModelForm):
	class Meta:
		model = Answer
		fields = ['text']
		labels = {'text': ''}

		widgets = {
			'text': forms.Textarea(attrs={
				'class' : 'form-control', 
				'placeholder' : 'Give your answer here.',
				})
		}

ask/qa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator
from taggit.models import Tag
from .models import *
from .forms import *

def test(request, *args, **kwargs):
    return HttpResponse('OK')

def index(request):
    questions = Question.objects.new()
    limit = request.GET.get('limit', 5)
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, limit)
    paginator.baseurl = '/?page='
    page = paginator.page(page)
    context = {'questions': page.object_list, 'paginator': paginator, 
                'page': page, 'order': 'new'}
    return render(request, 'index.html', context)

def popular (request):
    questions = Question.objects.popular()
    limit = request.GET.get('limit', 5)
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, limit)
    paginator.baseurl = '/popular/?page='
    page = paginator.page(page)
    context = {'questions': page.object_list, 'paginator': paginator, 
                'page': page, 'order': 'popular'}
    return render(request, 'index.html', context)

def tagged (request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    questions = Question.objects.popular().filter(tags=tag)
    limit = request.GET.get('limit', 5)
    page = request.GET.get('page', 1)
    paginator = Paginator(questions, limit)
    paginator.baseurl = f'/tagged/{slug}/?page='
    page = paginator.page(page)
    context = {'questions': page.object_list, 'paginator': paginator, 
                'page': page, 'tag_filter': tag}
    return render(request, 'index.html', context)


def question(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    answers = question.answer_set.order_by('-added_at')
    if request.method != 'POST':
        form = AnswerForm()
    else:
        form = AnswerForm(data=request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            url = question.get_url()
            return redirect(url)
    context = {'question': question, 'answers': answers, 'form': form}
    return render(request, 'question.html', context)

@login_required
def ask(request):
    if request.method != 'POST':
        form = AskForm()
    else:
        form = AskForm(data=request.POST)
        if form.is_valid():
            ask = form.save(commit=False)
            ask.author = request.user
            ask.save()
            form.save_m2m()
            url = ask.get_url()
            return redirect(url)
    context = {'form': form}
    return render(request, 'ask.html', context)

@login_required
def question_like(request, **kwargs):
    url_from = request.POST.get('url_from')
    question_id = request.POST.get('question_id')
    question = get_object_or_404(Question, id=question_id)
    if request.method == 'POST':
        user = request.user
        if question.likes.filter(id=user.id):
            question.likes.remove(user)
        else:
            question.likes.add(user)
    return redirect(url_from)

@login_required
def answer_like(request, **kwargs):
    url_from = request.POST.get('url_from')
    answer_id = request.POST.get('answer_id')
    answer = get_object_or_404(Answer, id=answer_id)
    if request.method == 'POST':
        user = request.user
        if answer.likes.filter(id=user.id):
            answer.likes.remove(user)
        else:
            answer.likes.add(user)
    return redirect(url_from)

@login_required
def answer_correct(request, **kwargs):
    answer_id = request.POST.get('answer_id')
    answer = get_object_or_404(Answer, id=answer_id)
    question = answer.question
    if request.method == 'POST' and request.user == question.author:
        answer.is_correct = not answer.is_correct
        answer.save()
    return redirect(question.get_url())

ask/qa/templates/a_like_button.html
<form action="{% url 'qa:answer_like' %}" method='POST'>
	{% csrf_token %}
	<input type='hidden' name='url_from' value='{{ url_from }}'>
	<input type='hidden' name='answer_id' value='{{ answer.id }}'>
	<button name='submit'>
		{% if is_liked %}
			LIKES: 
		{% else %}
			likes: 
		{% endif %}
		{{ likes_count }}
	</button>
</form>

ask/qa/templates/ask.html
{% extends "base.html" %}

{% block content %}
	<p>Ask your question:</p>
	<form action="{% url 'qa:ask' %}" method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Ask</button>
		<input type='hidden' name='next' value="{% url 'qa:index' %}" />
	</form>
{% endblock content %}

ask/qa/templates/base.html
{% load qa_tags %}

<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset='utf-8'>
	<title>Q&A</title>
</head>
<body>
	<div><p>
		<a href="{% url 'qa:index' %}">Q&A</a> | 
		<a href="{% url 'qa:ask' %}">Ask!</a> | 
		{% if user.is_authenticated %}
			<span>{{ user.username }}</span> | 
			<a href="{% url 'users:show_profile' %}">Settings</a> | 
			<a href="{% url 'users:logout' %}">Log out</a>
		{% else %}
			<a href="{% url 'users:login' %}">Log in</a> | 
			<a href="{% url 'users:signup' %}">Register</a>
		{% endif %}
	</p></div>
	<hr>
	{% show_popular_tags %}
	<div>
		{% block content %}{% endblock content %}
	</div>
</body>
</html>

ask/qa/templates/index.html
{% extends "base.html" %}
{% load likes_options %}

{% block content %}
	<h3 class="mt-1 mb-3">
		{% if order == 'new' %}
			<strong class="me-2">New questions</strong>
		{% else %}
			<a href="{% url 'qa:index' %}" class="me-2"><small>New questions</small></a>
		{% endif %}
		{% if order == 'popular' %}
			<strong>Hot questions</strong>
		{% else %}
			<a href="{% url 'qa:popular' %}"><small>Hot questions</small></a>
		{% endif %}
	</h3>
	{% if tag_filter %}
	  <h4 class=" text-muted mb-3"><strong>Filtered by 
		<span class="badge rounded-pill bg-primary text-dark bg-opacity-25 px-3 ms-1">
		  {{ tag_filter }}</span></strong>
		<a href="{% url 'qa:index' %}"><sup class="closing_cross">
			<span class="badge rounded-pill bg-secondary bg-opacity-75">x</span>
			</sup></a>
	  </h4>
	{% endif %}
  {% for question in questions %}
	<div class="card">
      <div class="card-body">
        <h4 class="card-title mb-3 mt-1">
          <a href="{% url 'qa:question' question.id %}" class="card-link">{{ question }}</a>
        </h4>
        <p class="card-text question_text">{{ question.text|truncatewords:50 }}</p>
        <div class="d-inline-flex align-items-center">
          {% q_like_button question user.id request.get_full_path %}
          <div class="card-text text-muted ms-4">Answers: {{ question.answer_set.count }}</div>
        </div>
        {% if question.tags.all %}
		  <div class="card-text text-muted mt-2">Tags: 
		    {% for tag in question.tags.all %}
		      <span class="popular_tag badge rounded-pill bg-primary bg-opacity-25 px-3 m-1">
		        <a href="{% url 'qa:tagged' tag.slug %}">{{ tag.name }} </a>
		      </span>
		    {% endfor %}
		  </div>
		{% endif %}  
		
      </div>
      <div class="card-footer text-muted d-inline-flex">
      	{% if question.author.profile.avatar %}
          <div class="avatar-footer" 
            style="background-image: url('{{ question.author.profile.avatar.url }}');">
          </div>
        {% endif %}
      	<div class="me-auto">
      	  by {{ question.author }}
      	</div>
      	<div>
      	  {{ question.added_at|time:"H:i" }} {{ question.added_at|date:"d.m.Y" }}
      	</div>
      </div>
    </div>
  {% endfor %}

  <nav aria-label="Page navigation example">
  	{% if paginator.num_pages > 1 %}
  	  <ul class="pagination">
	    {% for p in paginator.page_range %}
	    	{% if p == page.number %}
	    		<li class='page-item active'>
	    	{% else %}
	    		<li class='page-item'>
	    	{% endif %}
	    		<a class='page-link' href="{{ paginator.baseurl }}{{ p }}">{{ p }}</a>
	    	</li>
	    {% endfor %}
	  </ul>
	{% endif %}
  </nav>

{% endblock content %}

ask/qa/templates/popular_tags.html
<div class="popular_tags mx-2">
  <h4 class="mb-3 mt-1">Popular Tags</h4>
  <h5>			
  {% for tag in popular_tags %}
  	<span class="popular_tag badge rounded-pill bg-primary bg-opacity-25 px-3 m-1">
      <a href="{% url 'qa:tagged' tag.slug %}">{{ tag }}</a> 
    </span>
  {% endfor %}		
  </h5>
</div>

ask/qa/templates/q_like_button.html
{% load static %}

<form action="{% url 'qa:question_like' %}" method='POST'>
	{% csrf_token %}
	<input type='hidden' name='url_from' value='{{ url_from }}'>
	<input type='hidden' name='question_id' value='{{ question.id }}'>
	<button name='submit' class="btn btn-danger qlike">
		{% if is_liked %}
			<i class="fa-solid fa-heart"></i>
		{% else %}
			<i class="fa-regular fa-heart"></i>
		{% endif %}
		{{ likes_count }}
	</button>
</form>

ask/qa/templates/question.html
{% extends "base.html" %}
{% load likes_options %}

{% block content %}
  <div>
	<h3 class="mb-3 mt-1">{{ question }}</h3>
	<p class="question_text">{{ question.text }}</p>
	{% if question.tags.all %}
	  <p class="text-muted">Tags: 
	  	{% for tag in question.tags.all %}
	  	  <span class="popular_tag badge rounded-pill bg-primary bg-opacity-25 px-3 m-1">
	  	    <a href="{% url 'qa:tagged' tag.slug %}">#{{ tag.name }}</a> 
	  	  </span>
	  	{% endfor %}
	  </p>
	{% endif %}
	{% q_like_button question user.id request.path %}
	<div class="text-muted d-inline-flex w-100 mt-3">
      {% if question.author.profile.avatar %}
        <div class="avatar-footer" 
          style="background-image: url('{{ question.author.profile.avatar.url }}');">
        </div>
      {% endif %}
      <div class="me-auto">
        by {{ question.author }}
      </div>
      <div>
        {{ question.added_at|time:"H:i" }} {{ question.added_at|date:"d.m.Y" }}
      </div>
    </div>
  </div>
  <hr>
  <div>
  	{% if not answers %}
  	  <p>There is no answers yet.</p>
  	{% endif %}
	{% for answer in answers %}
	  <div class="card">
	  	{% if answer.is_correct %}
          <div class="card-body bg-primary bg-opacity-25">
        {% else %}
          <div class="card-body">
        {% endif %}
		  <p class="card-text">{{ answer.text }}</p>
		  <div class="d-inline-flex">
		  {% a_like_button answer user.id request.path %}
		  {% if user == question.author %}
		  	<form action="{% url 'qa:answer_correct' %}" method='POST'>
		  	  {% csrf_token %}
		  	    <input type='hidden' name='answer_id' value='{{ answer.id }}'>
		  	    <button name='submit' class="btn btn-primary ms-2 btn-sm">
		  	      {% if answer.is_correct %}
		  	      	Wrong! 
		  	      {% else %}
		  	      	Correct! 
		  	      {% endif %}
		  	    </button>
		  	</form>
		  {% endif %}
		  </div>
		</div>
		<div class="card-footer text-muted d-inline-flex">
          {% if answer.author.profile.avatar %}
            <div class="avatar-footer" 
              style="background-image: url('{{ answer.author.profile.avatar.url }}');">
            </div>
          {% endif %}
          <div>
            by {{ answer.author }}
          </div>
          {% if answer.is_correct %}
		    <div class="ms-auto"><b>Correct answer!</b></div>
		  {% endif %}
          <div class="ms-auto">
            {{ answer.added_at|time:"H:i" }} {{ answer.added_at|date:"d.m.Y" }}
          </div>
        </div>
	  </div>
	{% endfor %}
	<hr>
	{% if user.is_authenticated %}
	  <div class="mb-3">
		<form action="{% url 'qa:question' question.id %}" method='POST'>
			{% csrf_token %}
			{{ form.as_p }}
			<button name='submit' class="btn btn-primary">Send</button>
		</form>
	  </div>
	{% endif %}
  </div>
{% endblock content %}